import { Property, CityInfo, LocalityTrend } from './types';

export const CITIES_DATA: CityInfo[] = [
  {
    name: 'Mumbai',
    state: 'Maharashtra',
    code: 'MUM',
    popularLocalities: ['Andheri West', 'Bandra West', 'Powai', 'Worli', 'Juhu', 'Thane West', 'Kandivali East', 'Borivali West'],
    avgPricePerSqFt: 22400,
    yoyGrowth: 9.4,
    totalListingsCount: 38420,
    image: 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Bangalore',
    state: 'Karnataka',
    code: 'BLR',
    popularLocalities: ['Whitefield', 'Indiranagar', 'HSR Layout', 'Sarjapur Road', 'Electronic City', 'Bellandur', 'Hebbal', 'Koramangala'],
    avgPricePerSqFt: 8650,
    yoyGrowth: 14.8,
    totalListingsCount: 42150,
    image: 'https://images.unsplash.com/photo-1596176530529-78163a4f7af2?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Delhi / NCR',
    state: 'Delhi NCR',
    code: 'DEL',
    popularLocalities: ['Golf Course Extension Gurgaon', 'Sector 62 Noida', 'Dwarka Expressway', 'Vasant Kunj', 'Greater Noida West', 'Cyber City Gurgaon', 'South Extension'],
    avgPricePerSqFt: 11200,
    yoyGrowth: 12.1,
    totalListingsCount: 46200,
    image: 'https://images.unsplash.com/photo-1587474260584-136574528ed5?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Hyderabad',
    state: 'Telangana',
    code: 'HYD',
    popularLocalities: ['Gachibowli', 'Hitec City', 'Kondapur', 'Kokapet', 'Madhapur', 'Banjara Hills', 'Jubilee Hills', 'Financial District'],
    avgPricePerSqFt: 7800,
    yoyGrowth: 15.6,
    totalListingsCount: 29800,
    image: 'https://images.unsplash.com/photo-1605146769289-440113cc3d00?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Pune',
    state: 'Maharashtra',
    code: 'PUN',
    popularLocalities: ['Hinjawadi', 'Kharadi', 'Baner', 'Wakad', 'Viman Nagar', 'Koregaon Park', 'Hadapsar', 'Bavdhan'],
    avgPricePerSqFt: 7200,
    yoyGrowth: 10.3,
    totalListingsCount: 31400,
    image: 'https://images.unsplash.com/photo-1560518883-ce09059eeffa?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Chennai',
    state: 'Tamil Nadu',
    code: 'CHE',
    popularLocalities: ['OMR', 'Anna Nagar', 'Velachery', 'Adyar', 'Porur', 'Sholinganallur', 'ECR', 'Guindy'],
    avgPricePerSqFt: 7900,
    yoyGrowth: 8.7,
    totalListingsCount: 21500,
    image: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Kolkata',
    state: 'West Bengal',
    code: 'KOL',
    popularLocalities: ['New Town', 'Salt Lake', 'Rajarhat', 'EM Bypass', 'Ballygunge', 'Alipore', 'Behala', 'Garia'],
    avgPricePerSqFt: 6100,
    yoyGrowth: 7.2,
    totalListingsCount: 18900,
    image: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Ahmedabad',
    state: 'Gujarat',
    code: 'AMD',
    popularLocalities: ['SG Highway', 'Bopal', 'Satellite', 'Prahlad Nagar', 'Gota', 'Shela', 'Thaltej', 'GIFT City'],
    avgPricePerSqFt: 5400,
    yoyGrowth: 11.5,
    totalListingsCount: 16800,
    image: 'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=800&q=80',
  },
  {
    name: 'Lucknow',
    state: 'Uttar Pradesh',
    code: 'LKO',
    popularLocalities: ['Gomti Nagar', 'Amar Shaheed Path', 'Sushant Golf City', 'Hazratganj', 'Indira Nagar', 'Vibhuti Khand', 'Aliganj', 'Faizabad Road'],
    avgPricePerSqFt: 5250,
    yoyGrowth: 13.2,
    totalListingsCount: 14200,
    image: 'https://images.unsplash.com/photo-1598928506311-c55ded91a20c?auto=format&fit=crop&w=800&q=80',
  }
];

export const INITIAL_PROPERTIES: Property[] = [
  {
    id: 'mb-prop-101',
    title: '3 BHK Ultra Luxury Apartment in Godrej Woods',
    tagline: 'Nestled in an urban forest with 600+ mature trees and grand clubhouse',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Delhi / NCR',
    locality: 'Sector 62 Noida',
    subLocality: 'Near Metro & Expressways',
    price: 24500000,
    priceFormatted: '₹2.45 Cr',
    pricePerSqFt: 12564,
    maintenance: 6500,
    bhk: 3,
    bathrooms: 3,
    balconies: 3,
    carpetAreaSqFt: 1450,
    superBuiltUpAreaSqFt: 1950,
    furnishing: 'Semi-Furnished',
    floor: 14,
    totalFloors: 32,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraId: 'UPRERAPRJ7047',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600573472591-ee6b68d14c68?auto=format&fit=crop&w=1200&q=80',
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Experience lavish lifestyle living at Godrej Woods in Noida Sector 62. Featuring premium Italian marble flooring, VRV central air conditioning, German modular kitchen fittings, sprawling wrap-around balconies overlooking the lush private garden, and triple-tier biometric security.',
    amenities: [
      'Clubhouse (40,000 sq.ft)',
      'Temperature Controlled Infinity Pool',
      'Fully Equipped Gymnasium',
      'Squash & Badminton Courts',
      '24/7 Power Backup',
      'EV Charging Stations',
      'Multipurpose Hall',
      'Children Play Area with Splash Pool',
      'Jogging & Cycling Track'
    ],
    postedBy: {
      name: 'Godrej Properties Direct Desk',
      type: 'Builder',
      phone: '+91 98112 34567',
      companyName: 'Godrej Properties Ltd',
      responseTime: 'Under 15 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Noida Electronic City Metro', distance: '800 m', type: 'metro' },
      { name: 'Fortis Hospital Noida', distance: '1.2 km', type: 'hospital' },
      { name: 'Indirapuram Habitat Center', distance: '2.5 km', type: 'mall' },
      { name: 'Delhi Public School (DPS)', distance: '1.8 km', type: 'school' }
    ],
    createdAt: '2026-08-10'
  },
  {
    id: 'mb-prop-102',
    title: '4 BHK Luxury Sea-View High-Rise Flat in Bandra West',
    tagline: 'Panoramic Arabian Sea views with private elevator access & 3 reserved parkings',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Mumbai',
    locality: 'Bandra West',
    subLocality: 'Perry Cross Road',
    price: 98000000,
    priceFormatted: '₹9.80 Cr',
    pricePerSqFt: 40833,
    maintenance: 22000,
    bhk: 4,
    bathrooms: 5,
    balconies: 2,
    carpetAreaSqFt: 2400,
    superBuiltUpAreaSqFt: 3100,
    furnishing: 'Furnished',
    floor: 22,
    totalFloors: 28,
    facing: 'West',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '2 years',
    reraId: 'P51800018992',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: true,
    images: [
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Rare opportunity in quintessential Bandra West. Direct unobstructed sunset sea views, customized designer interiors by renowned architect, smart home automation with voice controls, imported Poggenpohl kitchen, walk-in closets, and private concierge lobby.',
    amenities: [
      'Private Lift Foyer',
      'Sky Lounge with Sea Views',
      'Heated Rooftop Pool',
      'Spa & Sauna Wellness Center',
      'Valet Parking & 3 Dedicated Basements',
      '24/7 Concierge and Doorman',
      'High-grade Acoustic Soundproofing',
      'Gymnasium with TechnoGym gear'
    ],
    postedBy: {
      name: 'Rohan Mehra (Owner)',
      type: 'Owner',
      phone: '+91 98200 98765',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Bandra Bandstand Promenade', distance: '900 m', type: 'mall' },
      { name: 'Lilavati Hospital', distance: '1.4 km', type: 'hospital' },
      { name: 'Bandra-Worli Sea Link Entrance', distance: '2.1 km', type: 'metro' },
      { name: 'St. Andrews High School', distance: '600 m', type: 'school' }
    ],
    createdAt: '2026-08-15'
  },
  {
    id: 'mb-prop-103',
    title: '3 BHK Gated Community Villa in Prestige Lakeside Habitat',
    tagline: 'Overlooking pristine Varthur Lake with Disney themed landscape & private lawn',
    listingType: 'buy',
    category: 'Villa',
    city: 'Bangalore',
    locality: 'Whitefield',
    subLocality: 'Varthur Main Road',
    price: 38500000,
    priceFormatted: '₹3.85 Cr',
    pricePerSqFt: 12419,
    maintenance: 8000,
    bhk: 3,
    bathrooms: 4,
    balconies: 3,
    carpetAreaSqFt: 2500,
    superBuiltUpAreaSqFt: 3100,
    furnishing: 'Semi-Furnished',
    floor: 1,
    totalFloors: 2,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '3 years',
    reraId: 'PRM/KA/RERA/1251/446/PR/170915/000176',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Stunning independent duplex villa in Prestige Lakeside Habitat spread across 102 acres of sprawling township. Features private garden, double-height ceiling living hall, solar water heating, 2 covered car ports, and access to 4 magnificent clubhouses.',
    amenities: [
      '4 Sprawling Clubhouses',
      'Olympic Size Swimming Pool',
      'Cricket Pitch & Tennis Courts',
      'Amphitheatre & Skating Rink',
      'Supermarket & Pharmacy inside campus',
      '100% DG Power Backup',
      'CCTV Survaillance with Smart App access',
      'Pet Friendly Green Parks'
    ],
    postedBy: {
      name: 'Prestige Certified Estates',
      type: 'Verified Agent',
      phone: '+91 80 4040 1234',
      companyName: 'Prime Realty Advisory',
      responseTime: 'Under 10 mins',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'ITPL Tech Park Whitefield', distance: '4.5 km', type: 'tech_park' },
      { name: 'Kadugodi Tree Park Metro', distance: '5.2 km', type: 'metro' },
      { name: 'Manipal Hospital Whitefield', distance: '3.8 km', type: 'hospital' },
      { name: 'The International School Bangalore (TISB)', distance: '4.1 km', type: 'school' }
    ],
    createdAt: '2026-08-18'
  },
  {
    id: 'mb-prop-104',
    title: '2 BHK Premium Fully Furnished Flat in HSR Layout',
    tagline: 'Ideal for tech startup founders & executives with 1 Gbps fiber & power backup',
    listingType: 'rent',
    category: 'Apartment',
    city: 'Bangalore',
    locality: 'HSR Layout',
    subLocality: 'Sector 2, Near 27th Main',
    price: 52000,
    priceFormatted: '₹52,000 / mo',
    pricePerSqFt: 43,
    maintenance: 4000,
    bhk: 2,
    bathrooms: 2,
    balconies: 2,
    carpetAreaSqFt: 980,
    superBuiltUpAreaSqFt: 1220,
    furnishing: 'Furnished',
    floor: 3,
    totalFloors: 5,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Available Immediately',
    ageOfProperty: '2 years',
    reraId: 'N/A - Standalone Gated',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Fully furnished, high-spec modern apartment in prime HSR Sector 2. Equipped with Samsung 55" Smart TV, double door refrigerator, Bosch front-load washing machine, ergonomic work desk with dual monitors setup, queen storage beds, modular kitchen with chimney, and 24hr power backup.',
    amenities: [
      '100% Power Backup (Inverter + Generator)',
      'High Speed Fiber Ready (up to 1 Gbps)',
      'Lift with Automatic Rescue Device',
      'Covered Car & Bike Parking',
      'Water Softener RO Plant',
      '24/7 Security Guard & Intercom'
    ],
    postedBy: {
      name: 'Dr. Arvind Rao (Owner)',
      type: 'Owner',
      phone: '+91 94480 55123',
      responseTime: 'Within 30 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Silk Board Junction Metro', distance: '1.8 km', type: 'metro' },
      { name: 'Cult.fit & Third Wave Coffee 27th Main', distance: '300 m', type: 'mall' },
      { name: 'Koramangala BDA Complex', distance: '2.4 km', type: 'mall' },
      { name: 'Narayana Multispeciality Hospital', distance: '1.1 km', type: 'hospital' }
    ],
    createdAt: '2026-08-20'
  },
  {
    id: 'mb-prop-105',
    title: '3 BHK High-Rise in My Home Bhooja, Gachibowli',
    tagline: 'Iconic Hyderabad landmark residence directly next to Financial District IT SEZs',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Hyderabad',
    locality: 'Gachibowli',
    subLocality: 'Silpa Gram Craft Village Road',
    price: 36000000,
    priceFormatted: '₹3.60 Cr',
    pricePerSqFt: 13953,
    maintenance: 7500,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    carpetAreaSqFt: 1950,
    superBuiltUpAreaSqFt: 2580,
    furnishing: 'Semi-Furnished',
    floor: 28,
    totalFloors: 36,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '2 years',
    reraId: 'P02400000109',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'My Home Bhooja stands tall as one of Hyderabad most prestigious high-rise gated addresses. Offers world-class clubhouse over 78,000 sq.ft, double-glazed soundproof glass facade, central gas piping, 3 car parkings, and panoramic views of the Durgam Cheruvu cable bridge skyline.',
    amenities: [
      '78,000 sq.ft Grand Clubhouse',
      'Heated Indoor & Outdoor Pools',
      'Double Level Tennis & Basketball Courts',
      'Supermarket, Bank ATM & Pharmacy',
      '24/7 High-Security Command Center',
      'Piped Gas with Smart Metering',
      'Billiards & Bowling Alley'
    ],
    postedBy: {
      name: 'Cybercity Elite Realty',
      type: 'Verified Agent',
      phone: '+91 40 6812 7700',
      companyName: 'Hyderabad Top Homes',
      responseTime: 'Under 10 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'IKEA Hyderabad & Inorbit Mall', distance: '1.5 km', type: 'mall' },
      { name: 'Raidurg Metro Station', distance: '1.2 km', type: 'metro' },
      { name: 'AIG Hospitals Gachibowli', distance: '2.0 km', type: 'hospital' },
      { name: 'Google & Microsoft Campus', distance: '2.5 km', type: 'tech_park' }
    ],
    createdAt: '2026-08-16'
  },
  {
    id: 'mb-prop-106',
    title: 'Grade A Plug & Play Commercial Office Space (120 Seats)',
    tagline: 'Fully furnished IT / Corporate office with conference suites & cafeteria in Hinjawadi Phase 1',
    listingType: 'commercial',
    category: 'Commercial Office',
    city: 'Pune',
    locality: 'Hinjawadi',
    subLocality: 'Phase 1, Rajiv Gandhi Infotech Park',
    price: 450000,
    priceFormatted: '₹4.50 Lac / mo',
    pricePerSqFt: 75,
    maintenance: 36000,
    bathrooms: 4,
    carpetAreaSqFt: 4800,
    superBuiltUpAreaSqFt: 6000,
    furnishing: 'Furnished',
    floor: 4,
    totalFloors: 10,
    facing: 'North',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraId: 'P52100021445',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Fully set up Grade A corporate office space with 120 modular workstations, 3 executive director cabins, 2 large meeting rooms with 85-inch video conferencing displays, 1 server room with dedicated precision AC, breakout cafeteria zone, and 12 reserved basement parkings.',
    amenities: [
      '100% N+1 DG Power Backup',
      'High-Speed Multi-ISP Optical Fiber Trunks',
      '24/7 Biometric Access Control & Turnstiles',
      'Centralised Chilled Water HVAC',
      'Dedicated Server Room with Fire Suppression',
      'Food Court in building campus'
    ],
    postedBy: {
      name: 'Vikas Deshmukh (Commercial Head)',
      type: 'Verified Agent',
      phone: '+91 20 6601 8899',
      companyName: 'Pune Commercial Connect',
      responseTime: 'Under 30 mins',
      rating: 4.7,
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Infosys & Wipro Phase 1 Campus', distance: '600 m', type: 'tech_park' },
      { name: 'Upcoming Hinjawadi Metro Line 3', distance: '400 m', type: 'metro' },
      { name: 'Courtyard by Marriott Hinjawadi', distance: '1.2 km', type: 'mall' },
      { name: 'Ruby Hall Clinic Hinjawadi', distance: '1.8 km', type: 'hospital' }
    ],
    createdAt: '2026-08-12'
  },
  {
    id: 'mb-prop-107',
    title: 'Luxury Single & Double Sharing PG with 3-Time Meals in Cyber City',
    tagline: 'All-inclusive co-living with housekeeping, high speed WiFi, gym & gaming zone',
    listingType: 'pg',
    category: 'PG / Co-Living',
    city: 'Delhi / NCR',
    locality: 'Cyber City Gurgaon',
    subLocality: 'DLF Phase 2, Near Rapid Metro',
    price: 18500,
    priceFormatted: '₹18,500 / mo',
    bhk: 1,
    bathrooms: 1,
    carpetAreaSqFt: 220,
    superBuiltUpAreaSqFt: 300,
    furnishing: 'Furnished',
    floor: 2,
    totalFloors: 4,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1540518614846-7eded433c457?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Modern luxury co-living hub designed for young working professionals in Gurgaon. Rent covers 3 buffet meals daily (North & South Indian cuisines), daily room housekeeping, 300 Mbps unlimited Wi-Fi, electricity & AC usage, washing machines, and rooftop chillout zone with PS5.',
    amenities: [
      '3-Time Buffet Meals & Tea/Coffee',
      'Daily Professional Housekeeping',
      'Air Conditioned Rooms with Attached Baths',
      'Rooftop Lounge with PS5 & Table Tennis',
      'Biometric Entry with 24/7 Security Guard',
      'Automated Laundry Facility'
    ],
    postedBy: {
      name: 'Stanza Living DLF Hub',
      type: 'Owner',
      phone: '+91 124 456 7890',
      companyName: 'UrbanStay Co-living',
      responseTime: 'Instant',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'DLF Phase 2 Rapid Metro', distance: '350 m', type: 'metro' },
      { name: 'Cyber Hub Food & Dining District', distance: '600 m', type: 'mall' },
      { name: 'DLF Cyber City Tech Towers', distance: '700 m', type: 'tech_park' },
      { name: 'Max Super Speciality Hospital', distance: '3.0 km', type: 'hospital' }
    ],
    createdAt: '2026-08-21'
  },
  {
    id: 'mb-prop-108',
    title: 'Gated Villa Plot (2400 sq.ft) in Godrej Palm Retreat',
    tagline: 'Corner plot with clear title, RERA registered, and immediate registry & construction approval',
    listingType: 'plot',
    category: 'Residential Plot',
    city: 'Delhi / NCR',
    locality: 'Dwarka Expressway',
    subLocality: 'Sector 150 Expressway Zone',
    price: 18000000,
    priceFormatted: '₹1.80 Cr',
    pricePerSqFt: 7500,
    bathrooms: 0,
    carpetAreaSqFt: 2400,
    superBuiltUpAreaSqFt: 2400,
    furnishing: 'Unfurnished',
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    reraId: 'UPRERAPRJ17500',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Corner East-facing residential villa plot in prestigious gated township. 60-ft wide blacktop road frontage, underground electrical & sewage infrastructure, manicured avenue plantation, bank loan pre-approved by SBI and HDFC up to 80%.',
    amenities: [
      'Gated Boundary Wall with Security Gate',
      'Underground Cabling & Sewage Connection',
      'Streetlights & Green Tree Canopy',
      'Township Clubhouse Access',
      'Water Supply Line & Over Head Tank'
    ],
    postedBy: {
      name: 'Sunil Verma (Channel Partner)',
      type: 'Verified Agent',
      phone: '+91 99100 44556',
      companyName: 'Expressway Lands Ltd',
      responseTime: 'Under 15 mins',
      rating: 4.6,
      avatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Dwarka Expressway Toll Plaza', distance: '1.8 km', type: 'metro' },
      { name: 'IGI Airport Delhi Terminal 3', distance: '18 mins drive', type: 'airport' },
      { name: 'Indira Gandhi Indoor Stadium', distance: '6.0 km', type: 'mall' }
    ],
    createdAt: '2026-08-14'
  },
  {
    id: 'mb-prop-109',
    title: '2 BHK Airy Lakeview Flat in Powai Hiranandani Gardens',
    tagline: 'Neoclassical architecture with vibrant community, schools, and high street cafes',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Mumbai',
    locality: 'Powai',
    subLocality: 'Hiranandani Gardens, Central Avenue',
    price: 29500000,
    priceFormatted: '₹2.95 Cr',
    pricePerSqFt: 31052,
    maintenance: 8500,
    bhk: 2,
    bathrooms: 2,
    balconies: 1,
    carpetAreaSqFt: 780,
    superBuiltUpAreaSqFt: 950,
    furnishing: 'Semi-Furnished',
    floor: 16,
    totalFloors: 26,
    facing: 'North',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '4 years',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: true,
    images: [
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Exquisite 2 BHK home located in the heart of Hiranandani Gardens, Powai. Offers serene Powai Lake breeze, walking distance to Galleria Shopping Arcade, Hiranandani Foundation School, and top multinatonal corporate offices like L&T, Crisil, and Nomura.',
    amenities: [
      'Forest Club & Gymnasium',
      'Olympic Swimming Pool',
      'Squash & Lawn Tennis Courts',
      'High Street Galleria with 200+ Shops',
      'Lush 5-acre Heritage Gardens & Dog Park',
      '24/7 Security with Boom Barriers'
    ],
    postedBy: {
      name: 'Powai Premier Properties',
      type: 'Verified Agent',
      phone: '+91 22 2570 1212',
      companyName: 'Hiranandani Resale Specialists',
      responseTime: 'Under 10 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'IIT Bombay Main Gate', distance: '1.2 km', type: 'school' },
      { name: 'Powai Lake Promenade', distance: '800 m', type: 'mall' },
      { name: 'Dr. L H Hiranandani Hospital', distance: '400 m', type: 'hospital' },
      { name: 'Kanjurmarg Metro / Railway', distance: '2.5 km', type: 'metro' }
    ],
    createdAt: '2026-08-17'
  },
  {
    id: 'mb-prop-110',
    title: '4 BHK Independent Luxury Villa with Private Pool in ECR',
    tagline: 'Beachfront serenity with private lap pool, landscaped lawn, and servant quarter',
    listingType: 'buy',
    category: 'Villa',
    city: 'Chennai',
    locality: 'ECR',
    subLocality: 'Injambakkam Beach Side',
    price: 49000000,
    priceFormatted: '₹4.90 Cr',
    pricePerSqFt: 11666,
    maintenance: 10000,
    bhk: 4,
    bathrooms: 5,
    balconies: 3,
    carpetAreaSqFt: 3600,
    superBuiltUpAreaSqFt: 4200,
    furnishing: 'Furnished',
    floor: 1,
    totalFloors: 2,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Bespoke coastal living along Chennai scenic East Coast Road. Features private saltwater swimming pool, expansive sundeck, teakwood floor finishes, 40 KVA silent diesel generator backup, and direct 2-minute walking path to the private quiet beach.',
    amenities: [
      'Private Swimming Pool with Sun Loungers',
      'Manicured Lawn & Coconut Grove',
      'Separate Driver & Maid Quarters',
      'Automated Solar Power Grid (10 kW)',
      'Perimeter Electric Fencing & CCTV'
    ],
    postedBy: {
      name: 'K. Balasubramanian (Owner)',
      type: 'Owner',
      phone: '+91 98400 33221',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'ECR Golden Beach', distance: '300 m', type: 'mall' },
      { name: 'Apollo Hospitals OMR', distance: '4.5 km', type: 'hospital' },
      { name: 'Mayajaal Multiplex & Entertainment', distance: '3.2 km', type: 'mall' }
    ],
    createdAt: '2026-08-19'
  },
  {
    id: 'mb-prop-111',
    title: '4 BHK Luxury Independent Villa in Gomti Nagar Extension',
    tagline: 'Private rooftop garden, servant quarters, and direct access to Shaheed Path',
    listingType: 'buy',
    category: 'Villa',
    city: 'Lucknow',
    locality: 'Gomti Nagar',
    subLocality: 'Gomti Nagar Extension, Sector 7',
    price: 26500000,
    priceFormatted: '₹2.65 Cr',
    pricePerSqFt: 7571,
    maintenance: 4500,
    bhk: 4,
    bathrooms: 4,
    balconies: 3,
    carpetAreaSqFt: 2800,
    superBuiltUpAreaSqFt: 3500,
    furnishing: 'Semi-Furnished',
    floor: 1,
    totalFloors: 2,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: 'New Construction',
    reraId: 'UPRERAPRJ9921',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Stunning modern independent villa in the posh neighborhood of Gomti Nagar Extension. Built with premium Teak wood doors, Italian marble flooring, solar water heating, and private lawn with 2 covered parking slots.',
    amenities: [
      'Private Terrace & Garden',
      'Gated Community with 24/7 Guards',
      'Modular Kitchen with Chimney',
      '100% Power Backup',
      'EV Charger Point',
      'Rainwater Harvesting'
    ],
    postedBy: {
      name: 'Ashish Verma (Owner)',
      type: 'Owner',
      phone: '+91 94150 12345',
      responseTime: 'Under 10 mins (Zero Brokerage)',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Phoenix Palassio Mall', distance: '1.2 km', type: 'mall' },
      { name: 'Medanta Super Specialty Hospital', distance: '2.5 km', type: 'hospital' },
      { name: 'Ekana International Cricket Stadium', distance: '1.8 km', type: 'metro' },
      { name: 'City Montessori School (CMS)', distance: '900 m', type: 'school' }
    ],
    createdAt: '2026-08-20'
  },
  {
    id: 'mb-prop-112',
    title: '3 BHK High-Rise Flat in Rishita Manhattan, Amar Shaheed Path',
    tagline: 'Modern clubhouse, panoramic city skyline view, near IT City & HCL Campus',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Amar Shaheed Path',
    subLocality: 'Sector 7, Gomti Nagar Extension',
    price: 11500000,
    priceFormatted: '₹1.15 Cr',
    pricePerSqFt: 6515,
    maintenance: 3200,
    bhk: 3,
    bathrooms: 3,
    balconies: 3,
    carpetAreaSqFt: 1380,
    superBuiltUpAreaSqFt: 1765,
    furnishing: 'Semi-Furnished',
    floor: 12,
    totalFloors: 22,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraId: 'UPRERAPRJ6682',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: false,
    priceDrop: true,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Immaculately maintained 3 BHK apartment in Rishita Manhattan on Shaheed Path. Close proximity to Lucknow IT City, airport expressway, top international schools, and shopping avenues.',
    amenities: [
      'Grand Clubhouse & Swimming Pool',
      'Jogging Track & Tennis Court',
      '24/7 Multi-tier CCTV Security',
      'Children Play Area',
      'High-speed Elevators'
    ],
    postedBy: {
      name: 'Rishita Developers Desk',
      type: 'Builder',
      phone: '+91 94151 98765',
      companyName: 'Rishita Developers',
      responseTime: 'Under 30 mins',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Lucknow Airport (CCS)', distance: '12 km', type: 'metro' },
      { name: 'Lulu Mall Lucknow', distance: '3.5 km', type: 'mall' },
      { name: 'DPS Shaheed Path', distance: '1.1 km', type: 'school' }
    ],
    createdAt: '2026-08-18'
  },
  {
    id: 'mb-prop-blr-101',
    title: '3 BHK Ultra Luxury High-Rise in Godrej Air, Whitefield',
    tagline: 'Centrally air-purified homes with 16 oxygenating garden zones next to ITPL',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Bangalore',
    locality: 'Whitefield',
    subLocality: 'Hoodi Main Road, Near ITPL',
    price: 21500000,
    priceFormatted: '₹2.15 Cr',
    pricePerSqFt: 11621,
    maintenance: 6200,
    bhk: 3,
    bathrooms: 3,
    balconies: 3,
    carpetAreaSqFt: 1420,
    superBuiltUpAreaSqFt: 1850,
    furnishing: 'Semi-Furnished',
    floor: 11,
    totalFloors: 24,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraId: 'PRM/KA/RERA/1251/446/PR/170330/000201',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: true,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80'
    ],
    floorPlanImage: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?auto=format&fit=crop&w=800&q=80',
    description: 'Breathtaking 3 BHK apartment in Godrej Air, Hoodi Whitefield. Features CTFA air purification systems inside each home, clubhouse with 4 tiers of fitness and wellness zones, expansive sunlit balconies, and 5-min walk to Hoodi Metro Station.',
    amenities: [
      'Centrally Treated Fresh Air (CTFA)',
      'Club Oxygen with Organic Cafe',
      'Temperature Controlled Infinity Pool',
      'Badminton & Squash Courts',
      '100% DG Power Backup',
      'EV Car Charging Station'
    ],
    postedBy: {
      name: 'Godrej Direct Advisory Desk',
      type: 'Builder',
      phone: '+91 80 4911 5000',
      companyName: 'Godrej Properties Bangalore',
      responseTime: 'Under 15 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Hoodi Metro Station', distance: '400 m', type: 'metro' },
      { name: 'ITPL Tech Park', distance: '1.5 km', type: 'tech_park' },
      { name: 'Phoenix Marketcity Mall', distance: '3.2 km', type: 'mall' },
      { name: 'Manipal Hospital Whitefield', distance: '2.8 km', type: 'hospital' }
    ],
    createdAt: '2026-08-22'
  },
  {
    id: 'mb-prop-blr-102',
    title: 'Gated Villa Plot (2400 sq.ft) in Brigade Oasis, Devanahalli',
    tagline: 'RERA approved masterplanned township plot near Bangalore International Airport',
    listingType: 'plot',
    category: 'Residential Plot',
    city: 'Bangalore',
    locality: 'Devanahalli',
    subLocality: 'Devanahalli Airport Corridor',
    price: 14500000,
    priceFormatted: '₹1.45 Cr',
    pricePerSqFt: 6041,
    bathrooms: 0,
    carpetAreaSqFt: 2400,
    superBuiltUpAreaSqFt: 2400,
    furnishing: 'Unfurnished',
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    reraId: 'PRM/KA/RERA/1250/303/PR/221123/005489',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1500530855697-b586d89ba3ee?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'East-facing prime residential villa plot situated in the 40-acre grand Brigade Oasis township. Clear legal "A-Khata" title with subterranean electrical lines, storm water drains, tree-lined 50-ft wide avenues, and bank loans pre-sanctioned.',
    amenities: [
      'Gated Security with Smart RFID Access',
      'Underground Cabling & Sewage Treatment',
      '20,000 sq.ft Township Clubhouse',
      'Avenue Trees & Landscaped Parks',
      '24/7 Water Supply & Overhead Storage'
    ],
    postedBy: {
      name: 'Suresh Kumar (Owner)',
      type: 'Owner',
      phone: '+91 98860 11223',
      responseTime: 'Direct Owner - 0% Brokerage',
      rating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Kempegowda Int. Airport (BLR)', distance: '12 mins drive', type: 'airport' },
      { name: 'Devanahalli DC Office Metro (Upcoming)', distance: '3.5 km', type: 'metro' },
      { name: 'KIADB Aerospace SEZ Tech Park', distance: '6.0 km', type: 'tech_park' }
    ],
    createdAt: '2026-08-23'
  },
  {
    id: 'mb-prop-blr-103',
    title: 'Grade-A Furnished Corporate IT Office (85 Workstations)',
    tagline: 'Plug-and-play tech office in Embassy TechVillage on Outer Ring Road Bellandur',
    listingType: 'commercial',
    category: 'Commercial Office',
    city: 'Bangalore',
    locality: 'Bellandur',
    subLocality: 'Outer Ring Road (ORR) Tech Corridor',
    price: 380000,
    priceFormatted: '₹3.80 Lac / mo',
    pricePerSqFt: 84,
    maintenance: 32000,
    bathrooms: 3,
    carpetAreaSqFt: 3800,
    superBuiltUpAreaSqFt: 4500,
    furnishing: 'Furnished',
    floor: 5,
    totalFloors: 12,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Fully equipped Grade-A commercial office with 85 ergonomic linear workstations, 3 executive glass manager cabins, 2 boardrooms with video conferencing systems, dedicated server room, cafeteria pantry, and 8 reserved basement parkings.',
    amenities: [
      '100% N+1 DG Power Backup',
      'Dual High-Speed Fiber Leased Lines',
      '24/7 Security & Access Control Gates',
      'Multi-cuisine Food Court in campus',
      'Centralized VRV Air Conditioning'
    ],
    postedBy: {
      name: 'Karthik Somayaji',
      type: 'Verified Agent',
      phone: '+91 80 4122 8899',
      companyName: 'Bangalore Commercial Realty',
      responseTime: 'Under 10 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Bellandur Blue Line Metro (Upcoming)', distance: '300 m', type: 'metro' },
      { name: 'Cisco, Wells Fargo & JP Morgan Campus', distance: 'Within 500 m', type: 'tech_park' },
      { name: 'Sakra World Hospital', distance: '1.2 km', type: 'hospital' }
    ],
    createdAt: '2026-08-24'
  },
  {
    id: 'mb-prop-blr-104',
    title: 'Luxury Studio & Single Room Co-Living with Meals in Koramangala',
    tagline: 'All-inclusive premium co-living with housekeeping, gigabit Wi-Fi & rooftop lounge',
    listingType: 'pg',
    category: 'PG / Co-Living',
    city: 'Bangalore',
    locality: 'Koramangala',
    subLocality: '4th Block, Near Sony World Signal',
    price: 19000,
    priceFormatted: '₹19,000 / mo',
    bhk: 1,
    bathrooms: 1,
    carpetAreaSqFt: 250,
    superBuiltUpAreaSqFt: 320,
    furnishing: 'Furnished',
    floor: 3,
    totalFloors: 5,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1595526114035-0d45ed16cfbf?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Designer co-living stay in the buzzing tech and startup hub of Koramangala 4th Block. Includes 3 nutritious daily meals, daily housekeeping, 500 Mbps high-speed WiFi, dedicated workstation in room, air conditioning, automatic washing machines, and rooftop terrace.',
    amenities: [
      '3-Time Daily Buffet Meals',
      'Daily Room Housekeeping & Linen Change',
      '500 Mbps High Speed Fiber WiFi',
      'Air Conditioning & Attached Bathroom',
      'Rooftop Community Lounge with TV & Pool Table',
      'Biometric Entry & 24/7 Security'
    ],
    postedBy: {
      name: 'Zolo / UrbanStay Koramangala Hub',
      type: 'Owner',
      phone: '+91 80 4567 1122',
      companyName: 'UrbanStay Co-living',
      responseTime: 'Instant',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
    },
    nearbyLandmarks: [
      { name: 'Sony World Signal 80ft Road', distance: '200 m', type: 'mall' },
      { name: 'Forum Mall Koramangala', distance: '1.2 km', type: 'mall' },
      { name: 'St. John’s Medical College Hospital', distance: '1.8 km', type: 'hospital' }
    ],
    createdAt: '2026-08-25'
  },
  {
    id: 'lko-owner-prop-1',
    title: '1 BHK Flat in Chandganj Garden, Lucknow',
    tagline: 'Well ventilated compact home with ready registry and immediate possession',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Chandganj Garden',
    subLocality: 'Chandganj Garden, Lucknow',
    price: 2000000,
    priceFormatted: '₹20 Lac',
    pricePerSqFt: 3809,
    maintenance: 800,
    bhk: 1,
    bathrooms: 1,
    balconies: 1,
    carpetAreaSqFt: 525,
    superBuiltUpAreaSqFt: 620,
    furnishing: 'Semi-Furnished',
    floor: 2,
    totalFloors: 4,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '2 years',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Charming 1 BHK flat located in the peaceful neighborhood of Chandganj Garden, Lucknow. 24/7 water supply, power backup, modular kitchen fittings, and close proximity to public transit.',
    amenities: ['24/7 Water Supply', 'Covered Bike Parking', 'Power Backup', 'Security Guard'],
    postedBy: {
      name: 'Pramod Kumar (Owner)',
      type: 'Owner',
      phone: '+91 94150 99881',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-28'
  },
  {
    id: 'lko-owner-prop-2',
    title: '3 BHK Flat in Chandganj Garden, Lucknow',
    tagline: 'Spacious 3 bedroom home with dedicated car parking & open balcony',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Chandganj Garden',
    subLocality: 'Chandganj Garden, Lucknow',
    price: 6000000,
    priceFormatted: '₹60 Lac',
    pricePerSqFt: 4424,
    maintenance: 1500,
    bhk: 3,
    bathrooms: 2,
    balconies: 2,
    carpetAreaSqFt: 1356,
    superBuiltUpAreaSqFt: 1550,
    furnishing: 'Semi-Furnished',
    floor: 3,
    totalFloors: 5,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Generously sized 3 BHK flat in Chandganj Garden, Lucknow. Features vitrified tile flooring, wide balcony with sunlight, lift access, and covered car parking.',
    amenities: ['Lift Access', 'Covered Car Parking', '24/7 Security', 'Borewell & Municipal Water'],
    postedBy: {
      name: 'Vivek Sharma (Owner)',
      type: 'Owner',
      phone: '+91 94151 77665',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-28'
  },
  {
    id: 'lko-owner-prop-3',
    title: '4 BHK Luxury Flat in Gomtinagar Extension, Lucknow',
    tagline: 'High-rise luxury residence with panoramic city views and clubhouse access',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Gomti Nagar',
    subLocality: 'Gomtinagar Extension, Lucknow',
    price: 34000000,
    priceFormatted: '₹3.40 Cr',
    pricePerSqFt: 9460,
    maintenance: 6000,
    bhk: 4,
    bathrooms: 4,
    balconies: 4,
    carpetAreaSqFt: 3594,
    superBuiltUpAreaSqFt: 4200,
    furnishing: 'Semi-Furnished',
    floor: 18,
    totalFloors: 24,
    facing: 'North-East',
    constructionStatus: 'Under Construction',
    possessionDate: 'Dec 2026',
    ageOfProperty: 'New Launch',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Flagship 4 BHK corner apartment in premier high-rise in Gomtinagar Extension. Features sprawling living areas, Italian marble, servant quarter, and 2 reserved basement parkings.',
    amenities: ['Clubhouse & Infinity Pool', 'Tennis Court', 'High-Speed Elevators', 'EV Charging Points', '24/7 Surveillance'],
    postedBy: {
      name: 'Rajeev Tandon (Owner)',
      type: 'Owner',
      phone: '+91 94150 44332',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-27'
  },
  {
    id: 'lko-owner-prop-4',
    title: '3 BHK Flat in Raj Bhavan Colony, Lucknow',
    tagline: 'VIP location with lush green surroundings and historic high-end address',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Raj Bhavan Colony',
    subLocality: 'Raj Bhavan Colony, Lucknow',
    price: 20000000,
    priceFormatted: '₹2 Cr',
    pricePerSqFt: 8908,
    maintenance: 4500,
    bhk: 3,
    bathrooms: 3,
    balconies: 3,
    carpetAreaSqFt: 2245,
    superBuiltUpAreaSqFt: 2650,
    furnishing: 'Semi-Furnished',
    floor: 4,
    totalFloors: 8,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '3 years',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: true,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566753376-12c8ab7fb75b?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Exclusive 3 BHK residence in prestigious Raj Bhavan Colony, Hazratganj corridor. Quiet green tree-lined streets, tight security, and unmatched central location.',
    amenities: ['Gated Security', 'Covered Parking', 'Power Backup', 'Landscaped Garden'],
    postedBy: {
      name: 'Sunita Saxena (Owner)',
      type: 'Owner',
      phone: '+91 94150 11229',
      responseTime: 'Direct Owner - Zero Brokerage',
      rating: 5.0,
      avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-27'
  },
  {
    id: 'lko-fresh-prop-1',
    title: '3 BHK Flat in Gomti Nagar, Lucknow',
    tagline: 'Sunlit corner flat with modern modular kitchen and airy balconies',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Gomti Nagar',
    subLocality: 'Gomti Nagar, Lucknow',
    price: 11000000,
    priceFormatted: '₹1.10 Cr',
    pricePerSqFt: 7096,
    maintenance: 2800,
    bhk: 3,
    bathrooms: 3,
    balconies: 2,
    carpetAreaSqFt: 1550,
    superBuiltUpAreaSqFt: 1800,
    furnishing: 'Semi-Furnished',
    floor: 5,
    totalFloors: 14,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Freshly listed 3 BHK flat in prime Gomti Nagar. Walking distance to banks, multiplexes, hospitals, and Lohia Park.',
    amenities: ['Clubhouse', 'Gymnasium', '24/7 Security', 'Covered Parking'],
    postedBy: {
      name: 'Gomti Realty Partners',
      type: 'Verified Agent',
      phone: '+91 94150 66778',
      companyName: 'Gomti Realty Group',
      responseTime: 'Under 15 mins',
      rating: 4.8,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-29'
  },
  {
    id: 'lko-fresh-prop-2',
    title: '3 BHK Premium Flat in Gomti Nagar, Lucknow',
    tagline: 'Designer interiors with wooden flooring in master bedroom & Italian fittings',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Gomti Nagar',
    subLocality: 'Gomti Nagar, Lucknow',
    price: 15000000,
    priceFormatted: '₹1.50 Cr',
    pricePerSqFt: 9677,
    maintenance: 3500,
    bhk: 3,
    bathrooms: 3,
    balconies: 3,
    carpetAreaSqFt: 1550,
    superBuiltUpAreaSqFt: 1920,
    furnishing: 'Furnished',
    floor: 9,
    totalFloors: 16,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: 'Ready',
    reraApproved: true,
    isVerified: true,
    isFeatured: true,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1600585152220-90363fe7e115?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Fully furnished 3 BHK home in premium Gomti Nagar high-rise. Top-of-the-line appliances, split ACs, Italian marble, and reserved basement parking.',
    amenities: ['Swimming Pool', 'Gym & Spa', 'Power Backup', '24/7 Security'],
    postedBy: {
      name: 'Ved Prakash Mishra',
      type: 'Verified Agent',
      phone: '+91 94150 78901',
      companyName: 'Lumero House Private Limited',
      responseTime: 'Under 10 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-29'
  },
  {
    id: 'lko-fresh-prop-3',
    title: '2 BHK Flat in Sushant Golf City, Lucknow',
    tagline: 'Serene golf course views with integrated township amenities & shopping mall',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Sushant Golf City',
    subLocality: 'Sushant Golf City, Lucknow',
    price: 6000000,
    priceFormatted: '₹60 Lac',
    pricePerSqFt: 5454,
    maintenance: 2000,
    bhk: 2,
    bathrooms: 2,
    balconies: 2,
    carpetAreaSqFt: 1100,
    superBuiltUpAreaSqFt: 1320,
    furnishing: 'Semi-Furnished',
    floor: 6,
    totalFloors: 14,
    facing: 'North-East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: '1 year',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Immaculate 2 BHK apartment in Sushant Golf City. Close to Lulu Mall, Medanta Hospital, and Shaheed Path.',
    amenities: ['Township Golf Course', 'Shopping Complex', '24/7 Security', 'Kids Play Zone'],
    postedBy: {
      name: 'Sanskaar Properties',
      type: 'Verified Agent',
      phone: '+91 94150 33445',
      companyName: 'Sanskaar Properties',
      responseTime: 'Under 15 mins',
      rating: 4.7,
      avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-28'
  },
  {
    id: 'lko-fresh-prop-4',
    title: '2 BHK Flat in Ayodhya Road, Lucknow',
    tagline: 'Fast appreciating corridor with 4-lane connectivity and ready possession',
    listingType: 'buy',
    category: 'Apartment',
    city: 'Lucknow',
    locality: 'Ayodhya Road',
    subLocality: 'Ayodhya Road, Lucknow',
    price: 5000000,
    priceFormatted: '₹50 Lac',
    pricePerSqFt: 4166,
    maintenance: 1600,
    bhk: 2,
    bathrooms: 2,
    balconies: 2,
    carpetAreaSqFt: 1200,
    superBuiltUpAreaSqFt: 1400,
    furnishing: 'Semi-Furnished',
    floor: 4,
    totalFloors: 10,
    facing: 'East',
    constructionStatus: 'Ready to Move',
    possessionDate: 'Immediate',
    ageOfProperty: 'Ready',
    reraApproved: true,
    isVerified: true,
    isFeatured: false,
    isExclusiveOwner: false,
    priceDrop: false,
    images: [
      'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?auto=format&fit=crop&w=1200&q=80',
      'https://images.unsplash.com/photo-1560185127-6ed189bf02f4?auto=format&fit=crop&w=1200&q=80'
    ],
    description: 'Well planned 2 BHK flat on prime Ayodhya Road corridor. High rental demand, wide roads, round-the-clock water and power backup.',
    amenities: ['Gated Security', 'Lift Access', 'Park & Play Area', 'Visitor Parking'],
    postedBy: {
      name: 'Akansha Srivastava',
      type: 'Verified Agent',
      phone: '+91 94151 55667',
      companyName: 'Bhumi Realtors',
      responseTime: 'Under 10 mins',
      rating: 4.9,
      avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=200&q=80'
    },
    createdAt: '2026-08-28'
  }
];

export const LOCALITY_TRENDS_DATA: LocalityTrend[] = [
  {
    locality: 'Gomti Nagar',
    city: 'Lucknow',
    avgPricePerSqFt: 6800,
    rentalYield: '4.9% p.a.',
    yoyGrowth: 14.1,
    livabilityScore: 9.3,
    topProjects: ['Omaxe Grand', 'Rishita Manhattan', 'Eldeco Greens'],
    overview: 'Lucknow’s most prime planned residential and commercial neighborhood. Known for luxury residences, sprawling parks, top universities, and world-class retail malls.'
  },
  {
    locality: 'Whitefield',
    city: 'Bangalore',
    avgPricePerSqFt: 8950,
    rentalYield: '4.8% p.a.',
    yoyGrowth: 15.2,
    livabilityScore: 9.2,
    topProjects: ['Prestige Lakeside', 'Godrej Splendour', 'Brigade Woods'],
    overview: 'Major IT hub connected with the Purple Metro Line. Huge demand from tech professionals with top international schools and lifestyle malls.'
  },
  {
    locality: 'Bandra West',
    city: 'Mumbai',
    avgPricePerSqFt: 46200,
    rentalYield: '2.9% p.a.',
    yoyGrowth: 8.9,
    livabilityScore: 9.6,
    topProjects: ['Rustomjee Paramount', 'Supreme Bori', 'Kalpataru Magnificence'],
    overview: 'The Queen of Suburbs. Iconic celebrity neighborhoods, world-class nightlife, historic promenades, and unmatched status symbol.'
  },
  {
    locality: 'Sector 62 Noida',
    city: 'Delhi / NCR',
    avgPricePerSqFt: 9800,
    rentalYield: '4.4% p.a.',
    yoyGrowth: 13.8,
    livabilityScore: 8.9,
    topProjects: ['Godrej Woods', 'ATS One Hamlet', 'Mahagun Mezzaria'],
    overview: 'Established institutional and corporate hub with direct Blue Line Metro connectivity and excellent road infrastructure to Delhi.'
  },
  {
    locality: 'Gachibowli',
    city: 'Hyderabad',
    avgPricePerSqFt: 8400,
    rentalYield: '5.2% p.a.',
    yoyGrowth: 16.5,
    livabilityScore: 9.4,
    topProjects: ['My Home Bhooja', 'Prestige High Fields', 'Aparna Sarovar'],
    overview: 'The epicenter of Hyderabad Silicon Valley. Proximity to Amazon, Google, Microsoft, and the Outer Ring Road.'
  },
  {
    locality: 'Hinjawadi',
    city: 'Pune',
    avgPricePerSqFt: 6900,
    rentalYield: '5.0% p.a.',
    yoyGrowth: 11.2,
    livabilityScore: 8.7,
    topProjects: ['Godrej 24', 'Kolte Patil Life Republic', 'VTP Blue Waters'],
    overview: 'Hub of over 400 IT companies employing 400,000+ tech professionals. Metro Line 3 nearing completion will boost capital appreciation.'
  }
];
